name: Build Hello World

on:
  push:
    branches:
      - master
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up GCC
      run: sudo apt-get install -y gcc

    - name: Compile hello.c
      run: gcc hello.c -o hello

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: hello
        path: hello
