name: Build Hello World

on:
  push:
    branches:
      - master
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: yt-dlp
      run: sudo apt-get install -y yt-dlp

    - name: download video
      run: yt-dlp --sleep-requests 1.5 --min-sleep-interval 60 --max-sleep-interval 90 -o foo https://www.youtube.com/watch?v=C4Rg3CrNGKw

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: foo
        path: foo
    - name: upload binaries to release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: hello
